import { useTranslations } from 'next-intl';
import { Link } from '@/i18n/navigation';
import { Badge } from '@/components/ui/badge';
import type { MethodView } from '@/lib/server-api';
import { JsonCodeBlock } from './JsonCodeBlock';
import { ParametersTable } from './ParametersTable';

interface Props {
  method: MethodView;
  providerName?: string;
  modelName?: string;
}

export function MethodPage({ method, providerName, modelName }: Props) {
  const t = useTranslations('docs');
  const path = `${method.providerCode}/${method.modelCode}/${method.code}`;
  const heading = [
    providerName ?? method.providerCode,
    modelName ?? method.modelCode,
    method.publicName,
  ].join(' / ');

  return (
    <article className="space-y-8">
      <header className="space-y-3">
        <h1 className="text-3xl font-semibold tracking-tight">{heading}</h1>
        <div className="font-mono text-sm text-muted-foreground">{path}</div>
        <div className="flex flex-wrap gap-2">
          {method.supportsSync ? <Badge>{t('syncSupported')}</Badge> : null}
          {method.supportsAsync ? <Badge variant="secondary">{t('asyncSupported')}</Badge> : null}
        </div>
        {method.description ? (
          <p className="text-sm text-muted-foreground">{method.description}</p>
        ) : null}
      </header>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold">{t('parameters')}</h2>
        <ParametersTable schema={method.parametersSchema} />
      </section>

      {method.exampleRequest !== undefined ? (
        <section className="space-y-3">
          <h2 className="text-xl font-semibold">{t('exampleRequest')}</h2>
          <JsonCodeBlock value={method.exampleRequest} />
        </section>
      ) : null}

      {method.exampleResponse !== undefined ? (
        <section className="space-y-3">
          <h2 className="text-xl font-semibold">{t('exampleResponse')}</h2>
          <JsonCodeBlock value={method.exampleResponse} />
        </section>
      ) : null}

      <section className="rounded-md border bg-muted/40 p-4 text-sm">
        {t.rich('seePricing', {
          link: (chunks) => (
            <Link href="/dashboard/pricing" className="underline">
              {chunks}
            </Link>
          ),
        })}
      </section>

      <footer className="border-t pt-4 text-xs text-muted-foreground">
        {t('autoGeneratedFooter')}
      </footer>
    </article>
  );
}
